### ISSUE TITLE
Issues with arbitrary selectors usage

### ISSUE THREAD

**Issue by pawelblaszczyk5** [tokenami/tokenami#366] opened 2024-10-19 20:21 UTC
When trying to use arbitrary selectors I encounter few errors

1. Parsing issues should be handled more gracefully, currently they skip the whole generation and I get stylesheet with content like `SyntaxError: Unexpected end of input` or `SyntaxError: Invalid token in pseudo element: SquareBracketBlock`. To replicate it, we can use the example from readme 😄  `'--{&:[data-state=open]}_border-color': 'var(--color_primary)'`
2. What is recommended way of using attributes with arbitrary selectors? Related to previous question (it'd be nice to update the readme example that throw error), I feel like `--{&[data-pending]}_color` should work, but it doesn't. I found that I can do this `--{&:is([data-pending])}_color`, but it feels a bit hacky 😅 
3. How hard would it be to add some typesafety to the arbitrary selector part? Even only at the TS plugin side?

**Comment by jjenzz** [comment] 2024-10-20 09:51
1. oops, that's my mistake in the docs. the error is correct and the docs should be `--{&[data-state=open]}_border-color': 'var(--color_primary)` (without colon since attribute are not pseudo selectors)
2. your `--{&[data-pending]}_color` example should work, i'll fix :)
3. i'm not keen on the idea of typesafety for arb stuff tbh, you don't get intellisense there in tailwind either for example and the idea is that arb things would be moved to theme values if you require type safety. is it possible to add a custom selector for your use-case?

**Comment by pawelblaszczyk5** [comment] 2024-10-20 09:54
> @pawelblaszczyk5 thanks for reporting these ☺️
> 
> 1. oops, that's my mistake in the docs. the error is correct and the docs should be `--{&[data-state=open]}_border-color': 'var(--color_primary)` (without colon since attributes are not pseudo selectors)
> 2. your `--{&[data-pending]}_color` example should work, i'll fix :)
> 3. i'm not keen on the idea of typesafety for arb stuff tbh, you don't get intellisense there in tailwind either for example and the idea is that arb things would be moved to theme values if you require type safety. is it possible to add a custom selector for your use-case?

Re 3) i worded it poorly. By type safety I mostly meant get some nice error if I write some incorrect syntax. It could be even be outputted by CLI

**Comment by jjenzz** [comment] 2024-10-20 10:02
it seems the issue is that because it didn't work for you, you felt it would be nice for tokenami to guide you to the correct syntax. the correct syntax is just whatever you would do in CSS. i'm curious that maybe if it had worked, would you have still requested this feature?  

i don't know if it's worth building a css parser into the ts plugin tbh but feel free to split that into a separate GH if you'd like us to think about this some more. that way, i can fix the other issues here and close this ticket ☺️

**Comment by pawelblaszczyk5** [comment] 2024-10-20 10:04
Of course, understandable, you’re right here with the first part 😃

**Closed** 2024-10-20 10:41 UTC
